schema=1
patch.version=2
core.min=26
core.max=26
file.count=1
patch.totalSize=1941
patch.action=update
revoked.versions=

file.0.path=projectui/roster.properties
file.0.source=v2/files/projectui/roster.properties
file.0.size=1941
file.0.sha256=7239e2b5d240e4781f8d743a0c0e0828eea2a40b68567bc7c1ae7e1c9dd2b523
