schema=2
patch.version=1
core.min=26
core.max=26
file.count=1
patch.totalSize=1934
patch.action=update
revoked.versions=

file.0.path=projectui/roster.properties
file.0.source=v1/files/projectui/roster.properties
file.0.size=1934
file.0.sha256=419416224ff2be21b5d2c5dbc430267b9cf797624ee124472081227b5e1ca538
