trust.version=1
valid.from.epoch=1791175207
valid.until.epoch=1822711207
minimum.patch.version=1
key.count=1

key.0.id=release-2026-01
key.0.status=trusted
key.0.algorithm=SHA256withRSA
key.0.valid.from.epoch=1791175207
key.0.valid.until.epoch=1822711207
key.0.publicKey=MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAnf2O608IwbAYB0po1iEM3ZY9g7wUhuMh7q64VMsQUaTrhmP0caU3Jtc9iXj3sTBKC427ZNN9t7hUCWPXM+u3NV+CQq2XM1JbMthN7k1PLveB4poYbGN60/jNn+4f6tXTl8iZ8C775rM1WVY6YB7IozTiEhCVWWYELJGG4jjBKlW/3FVSOIIbVbFOYNx8zIHoXnoMB0qjUaV6aIcSsBNsp//OfoFMr3UrL5HXud2BbVbQtQYVSOYym30MV3WzdrCgSORtRv1CBYhWGqK8TbeI9OGjUsulofJc7wmTzYFEBehPsrbW8ZZz84x484YYS31S5GuTPTmoefJqdQVBYkV0bLpupjS+ZLhqsinZX3LLwUUM8tTpEVGhUG5SYSj1gZJolq8kEyy9CtNv/ZnsT1nSwRpHw6oGHY0XZudf8R6cRA+0z/c+x9NSjeC0H8cGhVVIHmaOohrkN+SVwtZN9XSD29DThWatBm5PRZ38NItmjkttfCINOXPTc+3LsDZHpcTFAgMBAAE=
